# Generated by Django 5.0.2 on 2024-05-22 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('total_score', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('vibe', models.FloatField(default=0)),
                ('seat', models.FloatField(default=0)),
                ('coffee', models.FloatField(default=0)),
                ('plug', models.FloatField(default=0)),
                ('wifi', models.FloatField(default=0)),
                ('toilet', models.FloatField(default=0)),
                ('parking', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeCafeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeecafes.coffeecafe')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('score', models.FloatField()),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeecafes.coffeecafe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeecafes.review')),
            ],
        ),
    ]
