# Generated by Django 5.0.2 on 2024-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeecafe',
            name='parking',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coffeecafe',
            name='toilet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coffeecafe',
            name='wifi',
            field=models.FloatField(default=0),
        ),
    ]
