# Generated by Django 5.0.2 on 2024-06-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecafes', '0002_recocafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recocafe',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recocafe',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
