# Generated by Django 5.0.2 on 2024-03-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecafes', '0013_alter_coffeecafe_id_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
