# Generated by Django 5.0.2 on 2024-03-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecafes', '0015_alter_coffeecafeimage_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeecafeimage',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeecafes.coffeecafe'),
        ),
    ]
